---
AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: MIT License
Description: Create persistent resources Ethereum Swarm stack
Parameters:
  AvailabilityZone:
    Description: Availability zone to be used
    Type: AWS::EC2::AvailabilityZone::Name
  SwarmDataDiskSize:
    Description: Swarm data disk size in gigabytes
    Default: 50
    Type: Number

Resources:
  SwarmDataVolume:
    Type: AWS::EC2::Volume
    DeletionPolicy: Snapshot
    Properties:
      Size: !Ref SwarmDataDiskSize
      VolumeType: gp2
      AvailabilityZone: !Ref "AvailabilityZone"
  PublicIP:
    Type: AWS::EC2::EIP

Outputs:
  PublicIP:
    Description: Public IP address
    Value: !Ref 'PublicIP'
    Export:
      Name: SwarmPublicIP
  SwarmDataVolume:
    Description: Swarm Data Volume
    Value: !Ref  'SwarmDataVolume'
    Export:
      Name: SwarmDataVolume
  AvailabilityZone:
    Description: Availability Zone
    Value: !Ref  'AvailabilityZone'
    Export:
      Name: AvailabilityZone
